---
- name: Hello World Test
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Hello World
      command: echo "Hello World from Semaphore CI!"
      register: output

    - name: Show output
      debug:
        var: output.stdout

